image: node:latest

stages:   
  - prepare
  - build
  - test
  - lint

build-job:
  stage: build
  script:
    - yarn install
    - yarn build

unit-test-job:
  stage: test
  script:
    - yarn install
    - yarn test:ci

lint-test-job:
  stage: lint
  script:
    - yarn install
    - yarn lint
